// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data;

namespace Shop.Migrations
{
    [DbContext(typeof(AppDBContent))]
    partial class AppDBContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Shop.Data.Models.Car", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("shortDesc")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("longDesc")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("img")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("price")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<string>("isFavourite")
                    .IsRequired()
                    .HasColumnType("bit");

                b.Property<string>("available")
                    .IsRequired()
                    .HasColumnType("bit");

                b.Property<int?>("Categoryid")
                    .HasColumnType("int");

                b.HasKey("id")
                    .HasName("PrimaryKey_CarId");

                b.HasIndex("Categoryid");

                b.ToTable("Car");
            });

            modelBuilder.Entity("Shop.Data.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PrimaryKey_CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Shop.Data.Models.Car", b =>
                {
                    b.HasOne("Shop.Data.Models.Category", null)
                        .WithMany("cars")
                        .HasForeignKey("Categoryid");
                });

            modelBuilder.Entity("Shop.Data.Models.Category", b =>
                {
                    b.Navigation("cars");
                });
#pragma warning restore 612, 618
        }
    }
}
